### ISSUE TITLE
bash script in windows: using bash coming with gin ?

### ISSUE THREAD

**Issue by jcolomb** [tonic-team/synchronisation_scripts#5]
The current solution requires to install cygwin and get it in a specific location (the default location). it will also only work for the 64 version as it is in the name of that path. 
Update: it worked only because I had intalled gin-cli via the old installer. 2 problems with new installer: one needs to add cygwin bash to the path for the code to run and more difficult, cygwin cannot access Gin commands.

Newnote: datalad installation requires/propose to install git beforehand, that git version comes with gitbash. I have not tested that yet, but might be a better way to work on the long run.

@achilleas-k it seems gin comes with a bash version (when opening gin-shell.bat, I get bash -- version to work)
However, `bash git --version` is not working. Is there a way to get git commands to work inside that bash ? This would make things much simpler.

- [ ] test use with gitbash, since it is coming "with" datalad
- [ ] test on different PCs

- [ ]

**Comment by achilleas-k** [comment]
To use the bash that's bundled with the gin client everywhere, we'd have to add it to the user's path, like we used to do before.  That caused issues with other programs that have the same dependencies but may have conflicting version requirements.  We might be able to only add bash to the path, or we could make the scripts use the bash binaries bundled with gin-cli when installed on Windows.  In the latter case, bash and other programs bundled with gin-cli wouldn't be available in all shells by default.

**Comment by jcolomb** [comment]
I had a former gin-cli installation, therefore I could access it everywhere, but git commands do not work inside this bash. new problem, gin commands are not accessible in cygwin bash.

**Comment by jcolomb** [comment]
tried to add directly to cygwin, work only in the terminal application so far. (need to use -l, but then path cannot be relative, needed to use old code to get path correctly): works but is not straightforward. 

export PATH="C:\Users\juliette\Desktop\gincli\git\bin;C:\Users\juliette\Desktop\gincli\bin":$PATH	in batch profile

**Comment by jcolomb** [comment]
Question: 
- do we need cygwin, or could we do the same process with the msys bash (adding git, git annex and gin commands to it +  add it to the path in windows), as one needs to do it for cygwin anyway ?
- or would it be possible to add git annex and gin as packages in cygwin ? we would still need to set cygwin in the windows path, though.

note: it needs git annex, although I do not really understand why, if git annex not installed :

```
failed to initialise log file. 
[error] the commit command is not availlable...
failed to initialise log file. 
```

**Comment by jcolomb** [comment]
Alternative solution translating bash into .bat using AI, see #13

**Comment by jcolomb** [comment]
solution used: using datalad + portable python script. using a .bat script to call the python script.
